### ISSUE TITLE
getting issue no module named dotenv in cli following cmds run in readme.md video

### ISSUE THREAD

**Issue by noahehall** [apiiro/combobulator#8]
```sh
poop@spaceship:~/git/combobulator/src
04:29 PM (main=) $ python3 ./combobulator.py --help
Traceback (most recent call last):
  File "/.../combobulator/src/./combobulator.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'


```

**Comment by moshe-apiiro** [comment]
Hi, thank you for the note.

The message prompts you about a missing library.

Please run

`python3 -m pip install python-dotenv`

Two action items that I'm drawing from your note:
1. To add required step for installing dependencies
2. To allow a pipenv support through a Pipfile

**Comment by moshe-apiiro** [comment]
Added proper documentation.
@noahehall please try the suggested requirements installation.
